name = "ash/randr"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'ash/randr'"

[repository]
user = "ash"
project = "randr"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.5.0"
source = "github"
